<a href="https://colab.research.google.com/github/AhsanBilal157/Deep_learning_Assignments/blob/main/car_price_pridiction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Car Price Prediction::**

Download dataset from this link:


https://www.kaggle.com/hellbuoy/car-price-prediction


# **Problem Statement::**

A Chinese automobile company Geely Auto aspires to enter the US market by setting up their manufacturing unit there and producing cars locally to give competition to their US and European counterparts.

They have contracted an automobile consulting company to understand the factors on which the pricing of cars depends. Specifically, they want to understand the factors affecting the pricing of cars in the American market, since those may be very different from the Chinese market. The company wants to know:

Which variables are significant in predicting the price of a car How well those variables describe the price of a car Based on various market surveys, the consulting firm has gathered a large data set of different types of cars across the America market.

# **task::¶**
We are required to model the price of cars with the available independent variables. It will be used by the management to understand how exactly the prices vary with the independent variables. They can accordingly manipulate the design of the cars, the business strategy etc. to meet certain price levels. Further, the model will be a good way for management to understand the pricing dynamics of a new market.

## **WORKFLOW ::**
1.Load Data

2.Check Missing Values ( If Exist ; Fill each record with mean of its feature )

3.Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

4.Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).

5.Compilation Step (Note : Its a Regression problem , select loss , metrics according to it) 6.Train the Model with Epochs (100) and validate it

7.If the model gets overfit tune your model by changing the units , No. of layers , activation function , epochs , add dropout layer or add Regularizer according to the need .

8.Evaluation Step

9.Prediction

In [ ]:
import requests 
import numpy as np
import pandas as pd


In [ ]:
car_price_pridiction = pd.read_csv('CarPrice_Assignment.csv')
car_price_pridiction

car_ID  symboling                   CarName  ... citympg highwaympg    price
0         1          3        alfa-romero giulia  ...      21         27  13495.0
1         2          3       alfa-romero stelvio  ...      21         27  16500.0
2         3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3         4          2               audi 100 ls  ...      24         30  13950.0
4         5          2                audi 100ls  ...      18         22  17450.0
..      ...        ...                       ...  ...     ...        ...      ...
200     201         -1           volvo 145e (sw)  ...      23         28  16845.0
201     202         -1               volvo 144ea  ...      19         25  19045.0
202     203         -1               volvo 244dl  ...      18         23  21485.0
203     204         -1                 volvo 246  ...      26         27  22470.0
204     205         -1               volvo 264gl  ...      19         25  22625.0

[205 rows x 26 columns]

In [ ]:
car_price_pridiction.isnull()

car_ID  symboling  CarName  fueltype  ...  peakrpm  citympg  highwaympg  price
0     False      False    False     False  ...    False    False       False  False
1     False      False    False     False  ...    False    False       False  False
2     False      False    False     False  ...    False    False       False  False
3     False      False    False     False  ...    False    False       False  False
4     False      False    False     False  ...    False    False       False  False
..      ...        ...      ...       ...  ...      ...      ...         ...    ...
200   False      False    False     False  ...    False    False       False  False
201   False      False    False     False  ...    False    False       False  False
202   False      False    False     False  ...    False    False       False  False
203   False      False    False     False  ...    False    False       False  False
204   False      False    False     False  ...    False    False       False  False

[205 rows x 26 columns]

In [ ]:
car_price_pridiction.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [ ]:
#encode_data = pd.get_dummies(car_price_pridiction,columns=['CarName','fueltype','aspiration','doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber'])
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
car_price_pridiction['fueltype'] = labelencoder.fit_transform(car_price_pridiction['fueltype'])
car_price_pridiction['aspiration'] = labelencoder.fit_transform(car_price_pridiction['aspiration'])
car_price_pridiction['carbody'] = labelencoder.fit_transform(car_price_pridiction['carbody'])
car_price_pridiction['drivewheel'] = labelencoder.fit_transform(car_price_pridiction['drivewheel'])
car_price_pridiction['enginelocation'] = labelencoder.fit_transform(car_price_pridiction['enginelocation'])
car_price_pridiction['fuelsystem'] = labelencoder.fit_transform(car_price_pridiction['enginelocation'])

In [ ]:
car_price_pridiction["doornumber"] = car_price_pridiction["doornumber"].map({'two':2,'four':4})
car_price_pridiction['doornumber']

0      2
1      2
2      2
3      4
4      4
      ..
200    4
201    4
202    4
203    4
204    4
Name: doornumber, Length: 205, dtype: int64

In [ ]:
car_price_pridiction.head()

car_ID  symboling                   CarName  ...  citympg  highwaympg    price
0       1          3        alfa-romero giulia  ...       21          27  13495.0
1       2          3       alfa-romero stelvio  ...       21          27  16500.0
2       3          1  alfa-romero Quadrifoglio  ...       19          26  16500.0
3       4          2               audi 100 ls  ...       24          30  13950.0
4       5          2                audi 100ls  ...       18          22  17450.0

[5 rows x 26 columns]

In [ ]:
data1 = car_price_pridiction[['horsepower','boreratio','enginesize','curbweight','carwidth','carlength',
              'wheelbase','drivewheel','price','enginelocation']]

In [ ]:
data_x_input = data1.loc[:, data1.columns != 'price']
data_y_input = data1.loc[:,data1.columns == 'price']
from sklearn.model_selection import train_test_split

train_data,test_data,train_targets,test_targets =  train_test_split(data_x_input,data_y_input , test_size = 0.30 , random_state = 42)

In [ ]:
train_data

horsepower  boreratio  enginesize  ...  wheelbase  drivewheel  enginelocation
177          92       3.31         122  ...      102.4           1               0
75          175       3.78         140  ...      102.7           2               0
174          73       3.27         110  ...      102.4           1               0
31           76       2.91          92  ...       86.6           1               0
12          121       3.31         164  ...      101.2           2               0
..          ...        ...         ...  ...        ...         ...             ...
106         160       3.43         181  ...       99.2           2               0
14          121       3.31         164  ...      103.5           2               0
92           69       3.15          97  ...       94.5           1               0
179         161       3.27         171  ...      102.9           2               0
102         152       3.43         181  ...      100.4           1               0

[143 rows x 9 columns]

In [ ]:
mean= train_data.mean(axis=0)
train_data -= mean
std=train_data.std(axis=0)
train_data /= std

test_data -= mean
test_data /=std

In [ ]:
mean_label = train_targets.mean()
train_targets -= mean_label
std_label = train_targets.std()
train_targets /= std_label
test_targets -= mean_label
test_targets /= std_label


In [ ]:
train_targets


price
177 -0.275769
75   0.394985
174 -0.345972
31  -0.836497
12   0.965158
..        ...
106  0.636993
14   1.424028
92  -0.837262
179  0.330526
102  0.126428

[143 rows x 1 columns]

In [ ]:
test = np.array(test_data.iloc[:])

In [ ]:
train = np.array(train_data.iloc[:])

In [ ]:
test_l= np.array(test_targets.astype('float32'))

In [ ]:
train_l= np.array(train_targets.astype('float32'))

In [ ]:
from keras import models
from keras import layers

def build_model():
  model = models.Sequential()
  model.add(layers.Dense(10, input_shape=(train.shape[1],)))
  model.add(layers.Dense(8,))
  model.add(layers.Dense(6,activation = 'tanh'))
  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

In [ ]:
import numpy as np
k=4
num_val_samples = len(train) // k
num_epochs = 100
all_scores = []
for i in range(k):
  print('processing fold #', i)
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate(
  [train[:i * num_val_samples],
  train[(i + 1) * num_val_samples:]],
  axis=0)
  partial_train_l = np.concatenate(
  [train_l[:i * num_val_samples],
  train_l[(i + 1) * num_val_samples:]],
  axis=0)
  model = build_model()
  model.fit(partial_train_data, partial_train_l,
          epochs=num_epochs, batch_size=1, verbose=1)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=1)
  all_scores.append(val_mae)

processing fold # 0
Epoch 1/100
108/108 [==============================] - 1s 891us/step - loss: 0.8241 - mae: 0.5686
Epoch 2/100
108/108 [==============================] - 0s 906us/step - loss: 0.5190 - mae: 0.4394
Epoch 3/100
108/108 [==============================] - 0s 1ms/step - loss: 0.3322 - mae: 0.3663
Epoch 4/100
108/108 [==============================] - 0s 1ms/step - loss: 0.3745 - mae: 0.3750
Epoch 5/100
108/108 [==============================] - 0s 1ms/step - loss: 0.4826 - mae: 0.3972
Epoch 6/100
108/108 [==============================] - 0s 1ms/step - loss: 0.5648 - mae: 0.4061
Epoch 7/100
108/108 [==============================] - 0s 1ms/step - loss: 0.2708 - mae: 0.3361
Epoch 8/100
108/108 [==============================] - 0s 1ms/step - loss: 0.3346 - mae: 0.3361
Epoch 9/100
108/108 [==============================] - 0s 1ms/step - loss: 0.5117 - mae: 0.3954
Epoch 10/100
108/108 [==============================] - 0s 1ms/step - loss: 0.6158 - mae: 0.4743
Epoch 11/100
10

In [ ]:
all_scores

[0.23897016048431396,
 0.3004869222640991,
 0.3877061605453491,
 0.44558215141296387]

In [ ]:
model = build_model()
model.fit(train, train_l,
epochs=80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model.evaluate(test, test_l)

2/2 [==============================] - 0s 8ms/step - loss: 0.4140 - mae: 0.3533


In [ ]:
test_mae_score

0.3626048266887665

In [ ]:
test[20]

array([-0.53785762,  0.2549781 , -0.12100401, -0.31249553,  0.23428185,
        0.25346032, -0.02141514, -0.63899045, -0.11868111])

In [ ]:
x = model.predict(test[20].reshape(1,test.shape[1]))
x

array([[-0.41121632, -0.4037736 , -0.40242988, -0.4081468 , -0.41501772,
        -0.40409884]], dtype=float32)

In [ ]:
test[20].reshape(1,test.shape[1])

array([[-0.53785762,  0.2549781 , -0.12100401, -0.31249553,  0.23428185,
         0.25346032, -0.02141514, -0.63899045, -0.11868111]])